### ISSUE TITLE
Final trajectory has collision with the obstacle

### ISSUE THREAD

**Issue by VincentHFZ** [HKUST-Aerial-Robotics/grad_traj_optimization#2]
We test your code and compare it with your paper, [Gradient-Based Online Safe Trajectory for Quadrotor Flight in Complex Environments]. We have some questions about your project.

First, in your paper V-C, you mentioned that  you first optimize the collision cost only. All the free variables will be pushed to the basin of the distance field from the neighborhood of obstacles. Then re-allocate the time and re-parameterize  the trajectory to time according to current waypoints' postion. 
Although, we found in your code. The first-setp optimize the trajectory's smooth and obstacle.The second-step optimize obstacles, trajectory's smooth, velocity and acceleration, which conflict with your paper work.  We guess it is why sometime the final trajectory would have collision with the obstacles. 

![_20171221170940](https://user-images.githubusercontent.com/22048676/34248879-898da506-e672-11e7-8a4a-825468607483.jpg)

Second, sometimes the demo `random` would terminate like the image show below.  There is some bug maybe?

![_20171221170945](https://user-images.githubusercontent.com/22048676/34248901-995274bc-e672-11e7-9389-964d21f3e8dd.jpg)

@ZbyLGsc

**Comment by CuberXulong** [comment]
Ahhhhh, it's a very gooood question! I have the same Problem when I use this Package. Unfortunately, I have no idea either...

**Comment by USTfgaoaa** [comment]
Sorry for the problem and thanks for reporting that. Shortly speaking, that's because some bugs and we have fixed them, the code would be updated soon tonight.
Actually, the functionality should be consistent with the paper, as we did for all onboard flight test and simulation shown in the paper.  Originally all optimization code (the solver) is written by my hand and we planned to use off-the-shelf optimization solver (such as NLopt) to achieve better numerical performance, so we re-implemented the algorithm. As you can see, now the package is not in a plug-and-use stage, and we will keep updating and improving this package.

**Comment by VincentHFZ** [comment]
So, the reason your project code has some conflict with the paper is the re-implementation using NLopt, am I right? I wander why you changed the optimization process instead of just replacing the optimization solver. Would the changes of process get better effect? 
Furthermore, did the phenomenon, the final trajectory having collision with obstacles, occur when you test on your machine?

**Comment by USTfgaoaa** [comment]
Yes, that's right. And the most important reason is that this package is re-implemented by Boyu Zhou, not me, based on my code. Of course different people have different understanding even to one method. We have discussed about this yesterday and would fix it soon.

Actually we didn't change the entire optimization process and the problem occurred here is because the package is still in developing and there exist bugs. Using NLopt, the optimization procedure "at most time" runs faster and can get a lower objective cost. But sometimes it may diverge or converge very slowly, and we are still testing it.

For the last question, the "collision with obstacles" phenomenon should not occur. In our previous onboard flight tests for the IROS paper, it didn't occur; or the drone should have crashed.

Can all these above answer your question?

**Comment by USTfgaoaa** [comment]
We are testing the package and will update the code as soon as possible (in 1 or 2 days, as you know, Chrismas is approaching ^_^ )

**Comment by VincentHFZ** [comment]
Thanks for your answer. Marry Christmas. ^__^

**Comment by ZbyLGsc** [comment]
@VincentHFZ Thanks for your questions. This project is implemented by me, and I should clarify that the code does not _conflicting_ with the paper, but has some _slight_ changes. The most important change is that only collision cost is optimized firstly, as mentioned in the paper, while in this project both collision cost and smoothness cost are optimized in the first step. Both the formulation of cost function and the optimization process is actually the same. I made this change since I found optimizing both collision and smoothness cost firstly resulting in a smoother trajectory. And I will test it further.
 
As for the collision with obstacles, it should never happen and I will fix this bug.

**Comment by VincentHFZ** [comment]
After updating, the bug that the program terminate is less. We only see it occur once. Just as it shows below:

![456789](https://user-images.githubusercontent.com/22048676/34330389-f14da286-e956-11e7-947f-b1e9a4beda39.png)

Still have the situation that collision with obstacles, occur less though: 

![obstaclesoccur](https://user-images.githubusercontent.com/22048676/34330408-390cdec0-e957-11e7-9eea-2de3de9a9db5.png)

In your updates, you removed the first initial step for optimization, which make the success rate become lower maybe? (sometimes just optimize one, sometimes the try to optimize all  failed)

none optimization: 

![noneoptimization](https://user-images.githubusercontent.com/22048676/34330465-0fd103d2-e958-11e7-85ac-bc76415bdff7.png)

![123](https://user-images.githubusercontent.com/22048676/34330492-699df906-e958-11e7-9ad4-f2dbfe61335f.png)

optimize once only: 

![hihi](https://user-images.githubusercontent.com/22048676/34330501-80ea18d8-e958-11e7-93c1-075c3df6a751.png)

**Comment by USTfgaoaa** [comment]
Do you use WeChat? Add me "gaofei018883" please. I wanna ask more about the test you did.
